PACKAGE_NAME="intel-igpu-hwmon"
PACKAGE_VERSION="@PKGVER@"

BUILT_MODULE_NAME[0]="intel_igpu_hwmon"
DEST_MODULE_LOCATION[0]="/updates/dkms"

MAKE[0]="sh ${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build/build.sh ${kernel_source_dir} ${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build modules"
CLEAN="sh ${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build/build.sh ${kernel_source_dir} ${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build clean"

AUTOINSTALL="yes"
