#!/bin/sh
# Build-time feature detection for the out-of-tree GNA module.
# Distro kernels backport APIs, so LINUX_VERSION_CODE is unreliable; probe instead.
# Usage: [LLVM=1] conftest.sh <kernel-build-dir> <output-header>
set -u
KDIR="$1"; OUT="$2"
TMP=$(mktemp -d); trap 'rm -rf "$TMP"' EXIT
# The kernel must be built with the same toolchain it was compiled with, or
# every probe fails identically and the result is a silently wrong config.
# Detect from the target kernel's own config rather than trusting the caller,
# so this works on gcc and clang kernels alike (CachyOS ships clang+lld).
# Consult the FIRST config that exists and stop there. Falling through on a
# "not clang" answer would reach the running kernel's config, which is a
# different kernel than the one being built for: DKMS builds for kernels that
# are not running, and this box has a clang CachyOS kernel booted alongside a
# gcc Arch one. That mismatch builds a gcc kernel with LLVM=1, and every probe
# then fails identically, including the controls.
if [ -z "${LLVM:-}" ]; then
	for cfg in "$KDIR/.config" "$KDIR/../source/.config" "/proc/config.gz"; do
		[ -e "$cfg" ] || continue
		case "$cfg" in
			*.gz) zcat "$cfg" 2>/dev/null | grep -q "^CONFIG_CC_IS_CLANG=y" && LLVM=1 ;;
			*)    grep -q "^CONFIG_CC_IS_CLANG=y" "$cfg" 2>/dev/null && LLVM=1 ;;
		esac
		break
	done
fi
LLVM=${LLVM:-}

printf 'obj-m := probe.o\n' > "$TMP/Makefile"

# Compile only (probe.o), never link: modpost would fail on MODULE_LICENSE.
try() {
	cat > "$TMP/probe.c" <<EOF
#include <linux/module.h>
#include <linux/pm_runtime.h>
#include <drm/drm_drv.h>
#include <drm/drm_gem.h>
#include <drm/drm_gem_shmem_helper.h>
$1
EOF
	make -s -C "$KDIR" M="$TMP" ${LLVM:+LLVM=1} probe.o >/dev/null 2>&1
}

probe() {
	if try "$2"; then echo "#define $1 1" >> "$OUT"; echo "  $1 = yes" >&2
	else echo "/* #undef $1 */" >> "$OUT"; echo "  $1 = no" >&2; fi
	rm -f "$TMP"/probe.o "$TMP"/.probe.o.* 2>/dev/null
}

# Self-test: a probe that must pass and one that must fail. If either is
# wrong the harness is broken and every result below is meaningless.
try 'void gna_ct(struct drm_gem_object *o, struct iosys_map *m) { drm_gem_vmap(o, m); }' \
	|| { echo "conftest: positive control failed, harness broken" >&2; exit 1; }
rm -f "$TMP"/probe.o "$TMP"/.probe.o.* 2>/dev/null
try 'void gna_ct(void) { gna_no_such_symbol_xyzzy(); }' \
	&& { echo "conftest: negative control passed, harness broken" >&2; exit 1; }
rm -f "$TMP"/probe.o "$TMP"/.probe.o.* 2>/dev/null

{ echo "/* Generated by conftest.sh -- do not edit. */"
  echo "#ifndef GNA_CONFIG_H"; echo "#define GNA_CONFIG_H"; } > "$OUT"

probe GNA_HAVE_DRM_DRIVER_DATE \
	'static struct drm_driver gna_p = { .date = "x" };'
probe GNA_HAVE_SHMEM_PUT_PAGES_UNLOCKED \
	'void gna_p(struct drm_gem_shmem_object *s) { drm_gem_shmem_put_pages(s); }'
probe GNA_PM_RUNTIME_PUT_RETURNS_INT \
	'int gna_p(struct device *d) { return pm_runtime_put(d); }'
# accel_open is only declared under IS_ENABLED(CONFIG_DRM_ACCEL), so this
# probe fails on a kernel without the accel subsystem as well as one too old
# to have it at all.
probe GNA_HAVE_DRM_ACCEL \
	'#include <drm/drm_accel.h>
DEFINE_DRM_ACCEL_FOPS(gna_p_fops);
static struct drm_driver gna_p = { .driver_features = DRIVER_COMPUTE_ACCEL, .fops = &gna_p_fops };'

echo "#endif" >> "$OUT"
